In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from collections import Counter
class somecoolname:
    def __init__(self,X,Y,k):
        self.X1 = X
        self.Y = Y
        self.k = k
        area = self.X1.shape[2]*self.X1.shape[3]
        length = self.Y.shape[0]
        self.X = np.zeros((length,area))
        for i in range(length):
            self.X[i] = self.X1[i].flatten()
    def prepro(self,X):
        scaler = MinMaxScaler()
        return scaler.fit_transform(X)
    def rotate(self,X):
        return np.rot90(X,k = 1 , axes =(1,2))
    def predict(self,test_im):
        distances = []
        for i in range(self.Y.shape[0]):
            norm = 1e10
            for j in range(4):
                test_vector = test_im.flatten()
                curr = np.norm(test_vector - self.X[i])
                norm = min(norm,curr)
                test_im = rotate(test_im)
            distances.append(norm)
        distances = np.array(distances)
        indexes = np.argsort(distances)[:self.K]
        label = []
        for i in range(self.k):
            label.append(self.Y[indexes[i]])
        label = np.squeeze(np.array(label))
        return np.bincount(label).argmax()
    def checkacc(self,x_test_l,y_test_l =None):
        if(y_test_l!=None):
            predictions = []
            for i in range(y_test_l.shape[0]):
                y_test = y_test_l[i]
                y_pred = self.predict(x_test[i])
                predictions.append(y_pred-y_test)
            predictions = np.array(predictions)
            predictions = predictions.reshape((y_test_l.shape[0],1))
            accuracy = (y_test_l.shape[0] - np.count_nonzero(predictions))/y_test_l.shape[0]
            return predictions
        else :
            predictions = []
            for i in range(x_test.shape[0]):
                y_pred = self.predict(x_test[i])
                predictions.append(y_pred-y_test)
            predictions = np.array(predictions)
            predictions = predictions.reshape((x_test.shape[0],1))
            return predictions
        
    

In [1]:
import numpy as np

In [21]:
a = np.random.randint(-6,6,(10,3,4,4))

In [22]:
print(a)

[[[[-4 -3 -5  3]
   [ 4  3 -6 -2]
   [-1  2 -2  1]
   [-2 -6 -1 -3]]

  [[ 5  3  2  2]
   [-1  0 -5 -5]
   [-2 -2  1 -1]
   [ 5 -5 -1 -6]]

  [[-6 -2  3  5]
   [ 5  5  0 -6]
   [-2 -1 -2  3]
   [-2 -1 -4 -1]]]


 [[[ 2  2 -6 -1]
   [ 1 -3  4 -4]
   [ 2 -3 -3 -6]
   [ 3 -1 -2  2]]

  [[-6 -6 -2  1]
   [ 4 -3 -2  2]
   [ 4  5  4  3]
   [-3 -1 -2  1]]

  [[-4  3 -6 -4]
   [-5 -1 -2  4]
   [ 4 -1 -1  1]
   [-2  3  4 -4]]]


 [[[-2 -1 -2 -3]
   [-1  4  4 -2]
   [ 0 -3  4 -5]
   [-1  4 -1 -5]]

  [[-4  4  4 -1]
   [-6 -1 -3 -3]
   [-6  4  0 -6]
   [-1 -6  1  5]]

  [[ 0 -4 -6 -2]
   [ 2 -5  0 -1]
   [ 3  2  2  0]
   [ 5 -2 -5  0]]]


 [[[ 2 -5  3 -1]
   [-2 -4 -2 -6]
   [ 0 -6  3  4]
   [ 2 -3 -5  5]]

  [[ 2  0  2 -2]
   [-3  4  2  4]
   [ 4  3  2 -2]
   [ 3  4 -4  1]]

  [[ 5 -2 -3 -4]
   [ 5  3  1 -1]
   [-6 -3  1 -2]
   [ 0 -1  3 -6]]]


 [[[ 2  0 -1 -4]
   [ 3 -4  3  4]
   [-3  2  1 -4]
   [ 1  0 -3  0]]

  [[-4 -5 -2 -2]
   [ 4  2 -5  5]
   [-4  5 -6 -1]
   [-3  3 -4  1]]

  [[ 1 -5  4

In [24]:
print(a[0].shape)

(3, 4, 4)


In [12]:
print(a1)

[[[-2  3  5  3]
  [ 2 -6 -5  1]
  [ 3 -6  5  1]
  [ 5  3  2 -1]]

 [[-3  1 -3  4]
  [-6  5 -2 -1]
  [ 5 -2 -2  0]
  [ 4  3  1 -3]]

 [[ 3 -1  0 -4]
  [-5 -1 -1  0]
  [-6 -1  1 -4]
  [ 0  2  1  4]]]


In [15]:
a1 = a1.flatten()

In [16]:
print(a1)

[-2  3  5  3  2 -6 -5  1  3 -6  5  1  5  3  2 -1 -3  1 -3  4 -6  5 -2 -1
  5 -2 -2  0  4  3  1 -3  3 -1  0 -4 -5 -1 -1  0 -6 -1  1 -4  0  2  1  4]


In [17]:
a = np.zeros((3,48))
a[0]=a1

In [20]:
x = [1,99,3,4,45]
print(np.argsort(x))

[0 2 3 4 1]
